### ISSUE TITLE
What is EPICStools/ether_ip?

### ISSUE THREAD

**Issue by prjemian** [EPICS-synApps/support#18]
In `assemble_synApps.sh` there is a symbol for `ETHERIP` here: https://github.com/EPICS-synApps/support/blob/0623a478eae6c55a2378a8a07825b3a1c243b5ef/assemble_synApps.sh#L59

and here: https://github.com/EPICS-synApps/support/blob/0623a478eae6c55a2378a8a07825b3a1c243b5ef/assemble_synApps.sh#L199

Since `EPICSTools` only appears once in this file, should references to the `ether_ip` module remain in `assemble_synApps.sh`?

**Comment by keenanlang** [comment]
get_repo is set up to grab modules from more than just our set of modules. EPICSTools is the name of a github group and ether_ip is the repository name. Which, when put together, ends up with:

https://github.com/EPICStools/ether_ip

While it's not a standard module, people still might use it occasionally for a specific IOC.

**Comment by prjemian** [comment]
Fair enough.  Thanks for describing.
