### ISSUE TITLE
make distclean on top level does not remove "*.d" files

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [EPICS-synApps/support#23]
When I do "make distclean" under "support" or "areaDetector", I see the files with extension ".d" are not removed.
For example, ./pointGreyApp/src/).linux-x86_64-debug/pointGrey.d
If I issue the same command "make distclean" at "areaDetector/ADPointGrey", those files are removed, as I expected.
Is this the correct behavior or a bug in the make set up?

I've seen this behavior in more than one module (e.g. ADAndor3, ADBruker, ADPerkinElmer), so I think it's not specific to a driver.

**Comment by keenanlang** [comment]
Make distclean is defined in EPICS base and synApps doesn't do anything do alter the rules for that command. What version of EPICS base are you using and is it all the *.d files or just ones from a specific architecture?
