### ISSUE TITLE
create new installation wheel

### ISSUE THREAD

**Issue by prjemian** [EPICS-synApps/support#24]
Fixed a couple problems ([8a447dd2](https://github.com/EPICS-synApps/utils/commit/8a447dd264b05d3b24909c0f50da950336bf9377) & [d09e753](https://github.com/EPICS-synApps/utils/commit/d09e7533f55b641c5cb26341b59723c70a02b706)) that raised exceptions for Python 3.  Commit message describes each problem.

- [x] Bump the version number. (Currently 2.1, bump to 2.1.1)
- [x] Make a new wheel with these changes.

**Comment by prjemian** [comment]
Need to revise the [tiled-demo](https://github.com/prjemian/tiled-demo/blob/bbcb68a75b88d9eac7b99f1c8535df40a58d381f/environment.yml#L37) for this change.

**Comment by prjemian** [comment]
version info:

```bash
(tiled) prjemian@zap:~/.../EPICS-synApps/support$ git grep "2\.1" | grep -i version
documentation/synApps.html:			<li>the sequencer (version 2.1) uses re2c, which is not a standard part of
documentation/synAppsReleaseNotes.html:<li>Modified for serial-protocol version 2.1.
utils/mdaExplorer/mda.py:# version 2.1 Tim Mooney 2/15/2012
utils/mdaExplorer/mda.py:__version__ = '2.1'
utils/mdaPythonUtils/mda.py:# version 2.1 Tim Mooney 2/15/2012
utils/mdaPythonUtils/mda.py:__version__ = '2.1'
```

**Comment by prjemian** [comment]
@keenanlang Must we keep this line?  https://github.com/EPICS-synApps/support/blob/a94b312d8fe90106217968b3afdee34ff770c33d/.gitignore#L43

`git add -f` can be used to override in the mean time

**Comment by prjemian** [comment]
Follow the previous [steps](https://github.com/EPICS-synApps/utils/issues/3):

```bash
cd /tmp
git clone https://github.com/EPICS-synApps/support
cd support/utils/mdaPythonUtils
git checkout 24-new-mdalib-wheel
python setup.py bdist_wheel --universal
```

then copy the new wheel file (`dist/mdalib-2022.post9-py2.py3-none-any.whl`) back to this repo, commit and push.

**Comment by keenanlang** [comment]
> @keenanlang Must we keep this line?
> 
> https://github.com/EPICS-synApps/support/blob/a94b312d8fe90106217968b3afdee34ff770c33d/.gitignore#L43
> 
> `git add -f` can be used to override in the mean time

changed with [3447588](https://github.com/EPICS-synApps/support/commit/344758849b0bc9b6a214312615817d641a9368d2)
