### ISSUE TITLE
assemble_synApps.csh: iocStats module has lcls config

### ISSUE THREAD

**Issue by prjemian** [EPICS-synApps/support#4]
On using the `assemble_synApps.csh` script, the iocStats module contains a `RELEASE_SITE` file which requires editing for the synApps build to complete.  A successful revision was:

    ---: EPICS_SITE_TOP=/usr/local/lcls/epics
    ---: BASE_SITE_TOP=/usr/local/lcls/epics/base
    ---: MODULES_SITE_TOP=/usr/local/lcls/epics/modules/R3-14-12
    ---: IOC_SITE_TOP=/usr/local/lcls/epics/iocTop
    ---: EPICS_BASE_VER=base-R3-14-12

    +++: BASE_SITE_TOP=/opt/epics
    +++: EPICS_SITE_TOP=/opt/epics
    +++: EPICS_BASE_VER=/opt/epics/base-3.15.5

where `/opt/epics` is the local install location.  The point is to remove several definitions and redirect the remaining one away from the `lcls`-specific directories.

**Comment by prjemian** [comment]
Also want to set `MAKE_TEST_IOC_APP=NO` in `configure/RELEASE`

**Comment by timmmooney** [comment]
Thanks for this.  An alternative is to modify configure/RELEASE, and comment out the LCLS specific stuff.  As you note, configure/RELEASE must be modified in any case, so maybe it's better to modify only that file.

**Comment by keenanlang** [comment]
Fixed in 77c9024

assemble_synApps.sh now sets all necessary MACROS to build iocStats out of the box.
